server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: notification-service
  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:postgresql://ep-sweet-fog-ao2zppvf-pooler.c-2.ap-southeast-1.aws.neon.tech/notification-service?sslmode=require&channelBinding=require}
    username: ${NOTIFICATION_DB_USERNAME:neondb_owner}
    password: ${NOTIFICATION_DB_PASSWORD:npg_S7KmV3EJDxwt}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH:true}
          starttls:
            enable: ${SMTP_STARTTLS_ENABLE:true}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

notification:
  retry:
    fixed-delay-ms: ${NOTIFICATION_RETRY_DELAY_MS:300000}
    max-attempts: ${NOTIFICATION_RETRY_MAX_ATTEMPTS:3}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    com.cloudpos.notification: INFO
    org.hibernate.SQL: ${HIBERNATE_SQL_LOG_LEVEL:WARN}
