spring.application.name=pos
server.port=${SERVER_PORT:8080}

spring.datasource.url=${POS_DB_URL:jdbc:postgresql://ep-winter-block-a1xk2cx9-pooler.ap-southeast-1.aws.neon.tech/qalpos?sslmode=require&channelBinding=require}
spring.datasource.username=${POS_DB_USERNAME:neondb_owner}
spring.datasource.password=${POS_DB_PASSWORD:npg_dHc0Dy2JvLBA}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
